# Site settings
title:  Dev notes
#email: your-email@domain.com
description: "My dev dashboard to keeps notes, tips and tricks about dev and sys admin, vim, php, archlinux"
baseurl: ""
url: "http://tyjak.github.io"

# Build settings
markdown: kramdown
permalink: pretty
